outdir: "/data/huotong/project_tcr/2026May/output"
cellranger:
  reference_gex: "/data/huotong/Reference/cellranger/gex/refdata-gex-GRCh38-2024-A"
  reference_vdj: "/data/huotong/Reference/cellranger/vdj/refdata-cellranger-vdj-GRCh38-alts-ensembl-7.1.0"
  cellranger_path: "/data/huotong/Software/cellranger-9.0.1/cellranger"
  fastqc_path: "/data/huotong/Software/FastQC/fastqc"
  fastqc_threads: 20
  inner_enrichment_primers: "/data/huotong/MyCode/SingleCell_VDJ/example/config/inner-enrichment-primers.txt"
  localcores: 16
  localmem: 64
